name: Build librime with plugins using Musl

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:10.10
    steps:
      - name: Install dependencies
        run: |
          echo "deb [trusted=yes] https://community-packages.deepin.com/deepin/ apricot main contrib non-free" >> /etc/apt/sources.list
          apt update
          apt install -y cmake liblua5.3-dev pkgconf git build-essential

      - name: Clone librime repository
        run: |
          git clone https://github.com/rime/librime.git
          cd librime
          git submodule update --init

      - name: Modify leveldb CMakeLists.txt for compilation
        run: |
          cd librime
          sed -i '/check_library_exists(tcmalloc malloc "" HAVE_TCMALLOC)/a add_compile_options(-fPIC)' deps/leveldb/CMakeLists.txt

      - name: Install plugins
        run: |
          cd librime
          bash install-plugins.sh hchunhui/librime-lua lotem/librime-octagram

      - name: Run make deps
        run: |
          cd librime
          make deps

      - name: Install Boost
        run: |
          cd librime
          bash install-boost.sh
          # Boost download is slow, manually set BOOST_ROOT if needed
          export BOOST_ROOT=${PWD}/deps/boost-1.84.0

      - name: Modify CMakeLists.txt for static compilation and compatibility
        run: |
          cd librime
          # Change option(BUILD_STATIC to ON)
          sed -i 's/option(BUILD_STATIC "Build with dependencies as static libraries" OFF)/option(BUILD_STATIC "Build with dependencies as static libraries" ON)/' CMakeLists.txt

          ##sed -i '61a cmake_policy(SET CMP0144 NEW)\ncmake_policy(SET CMP0167 NEW)' CMakeLists.txt
          # Add compatibility for GCC < 9.0
          sed -i '/add_subdirectory(src)/a \
          if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")\n\
              execute_process(COMMAND ${CMAKE_CXX_COMPILER} -dumpversion OUTPUT_VARIABLE GCC_VERSION)\n\
              if(GCC_VERSION VERSION_LESS 9.0)\n\
                  cmake_policy(SET CMP0079 NEW)\n\
                  target_link_libraries(${rime_library} stdc++fs)\n\
              endif()\n\
          endif()' CMakeLists.txt

      - name: Build librime
        run: |
          cd librime
          make merged-plugins

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: librime-build
          path: librime/build/{lib,bin}  # Change path if needed based on actual build output
